name: build

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -B${{github.workspace}}/build -G "Unix Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target ci